import {
  int,
  timestamp,
  mysqlTable,
  primaryKey,
  varchar,
  serial,
  decimal,
  datetime,
} from "drizzle-orm/mysql-core";

export const mc = mysqlTable("MC", {
  id_mc: int("id_mc").notNull().primaryKey(),
  order_id: varchar("order_id", { length: 50 }),
  status: varchar("status", { length: 30 }),
  emp: varchar("emp", { length: 100 }),
  invoice: varchar("invoice", { length: 100 }),
  payment: varchar("payment", { length: 100 }),
  discount: decimal("discount", { precision: 10, scale: 3 }),
  sale: decimal("sale", { precision: 10, scale: 3 }),
  transport_service_provider: varchar("transport_service_provider", {
    length: 100,
  }),
  quantity: int("quantity", { unsigned: true }),
  shipping_cost: decimal("shipping_cost", { precision: 10, scale: 3 }),
  cod_cost: decimal("cod_cost", { precision: 10, scale: 3 }),
  tracking_number: varchar("tracking_number", { length: 100 }),
  channel: varchar("channel", { length: 100 }),
  channel_name: varchar("channel_name", { length: 100 }),
  name: varchar("name", { length: 200 }),
  phone: varchar("phone", { length: 50 }),
  address: varchar("address", { length: 255 }),
  subdistrict: varchar("subdistrict", { length: 100 }),
  district: varchar("district", { length: 100 }),
  province: varchar("province", { length: 100 }),
  zipcode: varchar("zipcode", { length: 30 }),
  pack_date: datetime("pack_date", { mode: "string" }),
  create_date: datetime("create_date", { mode: "string" }),
  paid_date: datetime("paid_date", { mode: "string" }),
  seller_discount: decimal("seller_discount", { precision: 10, scale: 3 }),
  platform_discount: decimal("platform_discount", { precision: 10, scale: 3 }),
  coin: decimal("coin", { precision: 10, scale: 3 }),
  sku_code: varchar("sku_code", { length: 100 }),
  product_name: varchar("product_name", { length: 300 }),
  product_options: varchar("product_options", { length: 100 }),
  price_per_piece: decimal("price_per_piece", { precision: 10, scale: 3 }),
  discount_per_piece: decimal("discount_per_piece", {
    precision: 10,
    scale: 3,
  }),
  quantity_product: decimal("quantity_product", { precision: 10, scale: 3 }),
  note: varchar("note", { length: 500 }),
  discount_per_product_p: decimal("discount_per_product_p", {
    precision: 10,
    scale: 3,
  }),
  shipping_cost_p: decimal("shipping_cost_p", { precision: 10, scale: 3 }),
  cod_cost_p: decimal("cod_cost_p", { precision: 10, scale: 3 }),
  sale_per_product_p: decimal("sale_per_product_p", {
    precision: 10,
    scale: 3,
  }),
  channel_p: varchar("channel_p", { length: 100 }),
  type_chit: varchar("type_chit", { length: 100 }),
  product_name_p: varchar("product_name_p", { length: 200 }),
});
